import {db} from "../../firebase/firebase.jsx";
import {collection, addDoc} from "firebase/firestore";
import React, { useState} from "react";

async function addCard (username, text) {
  await addDoc(collection(db, "cards"), {CreatedBy: username, Text: text, Category: "Generated By User", DrinkCount: 0, AnswerCount: 0})
}

function AddCardForm({ setNewCardActive }) {
  const [text, setText] = useState("");

  const HandleSubmit = async (e) => {
    e.preventDefault();
    if (text.trim() === "") return;


    await addCard("GET USERNAME", text);
    setText("");
    setNewCardActive(false);
  };

  return (
    <div className="card-form-popup">
      <div className="card-title-container">
        <h3>Put your question below</h3>
        <button className="close-button" onClick={() => setNewCardActive(false)}>X</button>
      </div>

      <div className="card-text-container">
        <form className="card-creation-form" onSubmit={HandleSubmit}>
          <textarea
            value={text}
            onChange={(e) => setText(e.target.value)}
            placeholder="What do you want to ask?"
            className="question-area"
          />
          <button className="submit-card-button" type="submit">
            Submit Card
          </button>
        </form>
      </div>
    </div>
  );
}
export default AddCardForm;