import "./App.css";
import "./css/home.css";
import React, { useState, useEffect, useRef } from "react";
import glassesIcon from "./assets/glasses.png";
import cardIcon from "./assets/cards.png";
import {db} from "./Firebase/firebase.jsx"
import {collection, addDoc} from "firebase/firestore";


function App() {
  const [players, setPlayers] = useState([]); 
  const [newCardActive, setNewCardActive] = useState(false);
  const wsRef = useRef(null);

  useEffect(() => {
  const ws = new WebSocket("ws://192.168.2.64:8082");
  wsRef.current = ws;
    ws.onopen = () => console.log("Connected!");

    ws.onmessage = (event) => {
      const msg = JSON.parse(event.data);
      if (msg.type === "updatePlayers") {
        setPlayers(msg.players);
      }
    };
    ws.onclose = () => console.log("Disconnected from the server");
    return () => ws.close();
  }, []);


  const handleAddPlayer = (name) => {
    if (name.trim() !== "") {
      wsRef.current.send(JSON.stringify({ type: "join", name}));
    }
  };
 

  return (
    <div className="home-container">
      <Navbar />
      <div className="bubble-container">
        <JoinBubble onJoin={handleAddPlayer} />
        <LobbyBubble players={players} />
      </div>
      <button className="add-card-button" onClick={() => setNewCardActive(true)}>
        <span className="btn-text">Add Card</span>
        <span className="btn-icon">
          <img src={cardIcon}></img>
        </span>
      </button>
      {newCardActive ? <AddCardForm setNewCardActive={setNewCardActive}/> : <div></div>}
    </div>
  );
}
export default App;

async function addCard (username, text) {
  await addDoc(collection(db, "cards"), {CreatedBy: username, Text: text, Category: "Generated By User", DrinkCount: 0, AnswerCount: 0})
}

function AddCardForm({ setNewCardActive }) {
  const [text, setText] = useState("");

  const HandleSubmit = async (e) => {
    e.preventDefault();
    if (text.trim() === "") return;

    await addCard("GET USERNAME", text);
    setText("");
    setNewCardActive(false);
  };

  return (
    <div className="card-form-popup">
      <div className="card-title-container">
        <h3>Put your question below</h3>
        <button className="close-button" onClick={() => setNewCardActive(false)}>X</button>
      </div>

      <div className="card-text-container">
        <form className="card-creation-form" onSubmit={HandleSubmit}>
          <textarea
            value={text}
            onChange={(e) => setText(e.target.value)}
            placeholder="What do you want to ask?"
            className="question-area"
          />
          <button className="submit-card-button" type="submit">
            Submit Card
          </button>
        </form>
      </div>
    </div>
  );
}
function JoinBubble({ onJoin }) {
  const [name, setName] = useState("");
  const [joined, setJoined] = useState(false); 

  const handleSubmit = (e) => {
    e.preventDefault();
    if (name.trim() === "") return;
    onJoin(name);
    setJoined(true); 
  };

  return (
    <div className="bubble">
      <div className="bubble-header">
        <h3>{joined ? "Welcome" : "Join Game"}</h3>
      </div>
      <div className="bubble-content">
        {!joined ? (
          <form className="form-content" onSubmit={handleSubmit}>
            <h3>Enter Your Name</h3>
            <input
              type="text"
              value={name}
              onChange={(e) => setName(e.target.value)}
              className="username-box"
            />
            <button className="submit-button" type="submit">
              Join
            </button>
          </form>
        ) : (
          <div className="welcome-message">
            <h3>Welcome {name}!</h3>
          </div>
        )}
      </div>
    </div>
  );
}



function LobbyBubble({ players }) {
  return (
    <div className="bubble">
      <div className="bubble-header">
        <h3>Lobby</h3>
      </div>
      <div className="bubble-content">
        <ol className="player-list">
          {players.map((player, index) => (
            <li key={index}>{player}</li>
          ))}
        </ol>
      </div>
    </div>
  );
}


function Navbar() {
  return (
    <div className="nav-main">
      <div className="title-container">
        <h2>Cards to Drink By</h2>
      </div>
      <div className="host-button-container">
        <button className="spectate-view">
          <span className="btn-text">Spectate</span>
          <span className="btn-icon"><img className="icon" src={glassesIcon}/></span>
        </button>
      </div>
    </div>
  );
}
